// Keyword -> emoji rules, checked in order (first match wins), so more
// specific keywords are listed before broad catch-alls like "computer" or
// "home". Verified against the full ~296-category taxonomy backing the
// catalog (server/data/UK_data.csv "categoryName" column) so every real
// category resolves to a distinct, sensible icon instead of falling back.
const ICON_RULES: Array<[string[], string]> = [
  [['3d print', '3d scan'], '🧊'],
  [['clock'], '🕐'],
  [['doormat'], '🚪'],
  [['slipcover'], '🛋️'],
  [['kvm', 'i/o port', 'port card'], '🖥️'],
  [['power suppl'], '🔋'],
  [['remote & app', 'app-controlled'], '📡'],
  [['music-making', 'music making'], '🎵'],
  [['video game', 'pc gaming', 'game accessor', 'game controller', 'gaming accessor'], '🎮'],
  [['game'], '🎲'],
  [['ballet', 'dancing'], '🩰'],
  [['equestrian'], '🐴'],
  [['ski ', 'skiing', 'snowboard', 'downhill ski', 'snow sled'], '🎿'],
  [['motorbike', 'motorcycle'], '🏍️'],
  [['car & motorbike', 'car & vehicle', 'automotive', ' car ', 'car&'], '🚗'],
  [['guitar', 'bass guitar'], '🎸'],
  [['piano', 'keyboard & digital instrument', 'synthesiser', 'sampler'], '🎹'],
  [['drum', 'percussion'], '🥁'],
  [['wind instrument', 'brass instrument'], '🎷'],
  [['string instrument'], '🎻'],
  [['dj & vj', 'dj equipment', 'karaoke', 'pa & stage'], '🎤'],
  [['microphone', 'recording & computer'], '🎙️'],
  [['headphone', 'earphone', 'hi-fi', 'speaker', 'home audio', 'radio', 'boombox', 'sound card', 'portable sound'], '🎧'],
  [['record player', 'cd, disc', 'tape player'], '📀'],
  [['camera', 'camcorder', 'lens', 'flash', 'tripod', 'monopod'], '📷'],
  [['binocular', 'telescope', 'optic'], '🔭'],
  [['print'], '🖨️'],
  [['scanner'], '🖨️'],
  [['cpu', 'motherboard', 'graphics card', 'computer memory', 'ram ', 'barebone pc', 'desktop pc', 'computer case', 'computer screw', 'server rack', 'power supply', 'uninterruptible'], '🖥️'],
  [['laptop'], '💻'],
  [['monitor'], '🖥️'],
  [['keyboard', 'mice', 'mouse', 'input device'], '⌨️'],
  [['tablet'], '📱'],
  [['mobile phone', 'smartphone', 'sim card', 'telephone', 'voip'], '📱'],
  [['e-book', 'ebook'], '📖'],
  [['smartwatch', 'wearable'], '⌚'],
  [['smart speaker', 'smart home', 'alexa'], '🔊'],
  [['surveillance', 'safety & security'], '📹'],
  [['router', 'networking device', 'network card', 'wi-fi', 'wifi'], '📶'],
  [['streaming', 'media player'], '📡'],
  [['projector'], '📽️'],
  [['television', ' tv ', 'home cinema', 'home entertainment'], '📺'],
  [['usb', 'hard drive', 'data storage', 'optical drive', 'hub'], '💾'],
  [['battery', 'batteries'], '🔋'],
  [['cable', 'adapter', 'plug', 'electrical'], '🔌'],
  [['light bulb', 'lighting', 'light', 'lamp'], '💡'],
  [['gps', 'finder'], '🧭'],
  [['torch', 'flashlight'], '🔦'],
  [['jigsaw', 'puzzle'], '🧩'],
  [['doll'], '🪆'],
  [['toy', 'kid', 'baby', 'child'], '🧸'],
  [['boy', 'girl'], '🧒'],
  [['footwear', 'shoe', 'sandal', 'boot', 'sneaker'], '👟'],
  [['dress', 'clothing', 'apparel', 'fashion', 'wear', 'handmade clothing'], '👗'],
  [['men'], '👔'],
  [['women'], '👗'],
  [['jewel'], '💍'],
  [['watch'], '⌚'],
  [['bag', 'wallet', 'backpack', 'luggage', 'travel gear'], '👜'],
  [['eyewear', 'sunglass'], '🕶️'],
  [['belt', 'tie', 'muffler', 'headwear'], '🧣'],
  [['beauty', 'cosmetic', 'make-up', 'makeup', 'skin care', 'hair care', 'manicure', 'pedicure', 'fragrance', 'personal care'], '💄'],
  [['health', 'medical'], '🩺'],
  [['supplement'], '💊'],
  [['kitchen', 'bakeware', 'cookware', 'tableware', 'dining'], '🍳'],
  [['coffee', 'espresso', 'tea '], '☕'],
  [['beer', 'wine', 'spirit', 'drink', 'grocery', 'food'], '🍷'],
  [['bath', 'bathroom'], '🛁'],
  [['bedding', 'bedroom', 'mattress', 'pillow'], '🛏️'],
  [['living room', 'furniture', 'sofa', 'hallway', 'office furniture', 'bar furniture'], '🛋️'],
  [['curtain', 'blind', 'window treatment', 'rug', 'cushion', 'mirror', 'vase', 'decor', 'décor', 'photo frame', 'digital frame', 'candle', 'sign', 'plaque'], '🖼️'],
  [['storage & home organisation', 'storage & organisation', 'box', 'organiser'], '📦'],
  [['packaging', 'shipping'], '📦'],
  [['cleaning', 'vacuum', 'floorcare', 'ironing', 'steamer'], '🧹'],
  [['fireplace', 'stove', 'heating', 'cooling', 'air quality'], '🔥'],
  [['plumbing', 'hydraulic', 'pneumatic', 'water cooler', 'water filter'], '🚰'],
  [['garden', 'plant', 'seed', 'bulb', 'decking', 'fencing', 'mower', 'outdoor power'], '🌱'],
  [['pool', 'hot tub'], '🏊'],
  [['camping', 'hiking', 'warmer'], '🏕️'],
  [['boating', 'sail'], '⛵'],
  [['cycling'], '🚴'],
  [['climbing'], '🧗'],
  [['basketball'], '🏀'],
  [['tennis', 'table tennis'], '🎾'],
  [['golf'], '⛳'],
  [['cricket'], '🏏'],
  [['boxing'], '🥊'],
  [['bowling'], '🎳'],
  [['billiard', 'snooker', 'dart'], '🎱'],
  [['trampoline'], '🤸'],
  [['sport', 'outdoor'], '⚽'],
  [['gift'], '🎁'],
  [['bird', 'wildlife', 'pet'], '🐾'],
  [['hobbies', 'hobby'], '🎯'],
  [['art & craft', 'arts & crafts', 'craft supplies', 'painting', 'handmade artwork'], '🎨'],
  [['handmade'], '🧵'],
  [['book', 'education', 'school', 'learning', 'writing', 'pen', 'pencil', 'calendar', 'organiser'], '📚'],
  [['office electronics', 'office supplies', 'office paper'], '🖇️'],
  [['agricultural'], '🚜'],
  [['construction', 'building supplies', 'hardware'], '🏗️'],
  [['tool', 'hand tool', 'power tool', 'cutting', 'abrasive', 'finishing'], '🔧'],
  [['industrial', 'material handling', 'test & measurement', 'thermometer', 'meteorological'], '🔬'],
  [['scientific', 'lab '], '🔬'],
  [['large appliance'], '🧊'],
  [['small kitchen appliance'], '🍴'],
  [['most loved'], '❤️'],
  [['computer', 'electronic', 'appstore'], '💻'],
  [['home', 'living'], '🏠'],
];

export const FALLBACK_CATEGORY_ICON = '🏷️';

export default function categoryIcon(name: string): string {
  const key = (name || '').toLowerCase();

  for (const [keywords, icon] of ICON_RULES) {
    if (keywords.some((keyword) => key.includes(keyword))) {
      return icon;
    }
  }

  return FALLBACK_CATEGORY_ICON;
}
