export default (app) => {
  app.post(
    `/tenant/:tenantId/product`,
    require('./productCreate').default,
  );
  app.put(
    `/tenant/:tenantId/product/:id`,
    require('./productUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/product/import`,
    require('./productImport').default,
  );
  app.post(
    `/tenant/:tenantId/product/import-huggingface`,
    require('./productImportHuggingFace').default,
  );
  app.delete(
    `/tenant/:tenantId/product`,
    require('./productDestroy').default,
  );
  app.delete(
    `/tenant/:tenantId/product/deleteAll`,
    require('./productDestroyAllRecords').default,
  );
  app.get(
    `/tenant/:tenantId/product/autocomplete`,
    require('./productAutocomplete').default,
  );

    app.get(
    `/tenant/:tenantId/product/autocomplete/product`,
    require('./productAutocompleteProduct').default,
  );
  app.get(
    `/tenant/:tenantId/product/browse/:id`,
    require('./productBrowseFind').default,
  );
  app.get(
    `/tenant/:tenantId/product/browse`,
    require('./productBrowse').default,
  );
  app.get(
    `/tenant/:tenantId/product`,
    require('./productList').default,
  );
  app.get(
    `/tenant/:tenantId/product/:id`,
    require('./productFind').default,
  );
  app.get(
    `/tenant/:tenantId/grap`,
    require('./grapOrders').default,
  )
};
