export default (app) => {
  // Public browse endpoints: no :tenantId param and no auth required, so
  // these must be registered without the /tenant/:tenantId prefix used by
  // the rest of this router (that prefix is what triggers tenantMiddleware).
  app.get(
    `/product/browse-public/:id`,
    require('./productBrowseFindPublic').default,
  );
  app.get(
    `/product/browse-public`,
    require('./productBrowsePublic').default,
  );
  app.post(
    `/tenant/:tenantId/product`,
    require('./productCreate').default,
  );
  app.put(
    `/tenant/:tenantId/product/:id`,
    require('./productUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/product/import`,
    require('./productImport').default,
  );
  app.post(
    `/tenant/:tenantId/product/import-huggingface`,
    require('./productImportHuggingFace').default,
  );
  app.get(
    `/tenant/:tenantId/product/import-huggingface/status`,
    require('./productImportSampleStatus').default,
  );
  app.delete(
    `/tenant/:tenantId/product`,
    require('./productDestroy').default,
  );
  app.delete(
    `/tenant/:tenantId/product/deleteAll`,
    require('./productDestroyAllRecords').default,
  );
  app.get(
    `/tenant/:tenantId/product/autocomplete`,
    require('./productAutocomplete').default,
  );

    app.get(
    `/tenant/:tenantId/product/autocomplete/product`,
    require('./productAutocompleteProduct').default,
  );
  app.get(
    `/tenant/:tenantId/product/browse/:id`,
    require('./productBrowseFind').default,
  );
  app.get(
    `/tenant/:tenantId/product/browse`,
    require('./productBrowse').default,
  );
  app.get(
    `/tenant/:tenantId/product`,
    require('./productList').default,
  );
  app.get(
    `/tenant/:tenantId/product/:id`,
    require('./productFind').default,
  );
  app.get(
    `/tenant/:tenantId/grap`,
    require('./grapOrders').default,
  )
};
