
import Permissions from 'src/security/permissions';
import { i18n } from 'src/i18n';
import config from 'src/config';

const permissions = Permissions.values;

export default [
  {
    id: '0',
    path: '/user',
    exact: true,
    icon: 'fas fa-users',
    label: i18n('dashboard.menu'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.userRead,
  },

  {
    id: '0',
    path: '/company',
    exact: true,
    icon: 'fa-solid fa-building',
    label: i18n('dashboard.company'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.userRead,
  },
  {
    id: '0',
    path: '/settings',
    exact: true,
    icon: 'fas fa-gear',
    label: i18n('settings.menu'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.settingsEdit,
  },

  {
    id: '0',
    path: '/transaction/deposit',
    exact: true,
    icon: 'fas fa-arrow-down',
    label: i18n('entities.transaction.deposit.menu'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/transaction/withdraw',
    exact: true,
    icon: 'fas fa-arrow-up',
    label: i18n('entities.transaction.withdraw.menu'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/product',
    exact: true,
    icon: 'fas fa-shirt',
    label: i18n('dashboard.product'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/product-category',
    exact: true,
    icon: 'fas fa-tags',
    label: i18n('dashboard.productCategory'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.productCategoryRead,
  },
  {
    id: '0',
    path: '/worker',
    exact: true,
    icon: 'fas fa-user-tie',
    label: i18n('dashboard.worker'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.workerRead,
  },
  {
    id: '0',
    path: '/wallet-settings',
    exact: true,
    icon: 'fas fa-wallet',
    label: i18n('dashboard.walletSettings'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.walletSettingsEdit,
  },
  {
    id: '0',
    path: '/store',
    exact: true,
    icon: 'fas fa-store',
    label: i18n('dashboard.store'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.storeRead,
  },
  {
    id: '0',
    path: '/delivery-address',
    exact: true,
    icon: 'fas fa-location-dot',
    label: i18n('dashboard.deliveryAddress'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.deliveryAddressRead,
  },
  {
    id: '0',
    path: '/notification',
    exact: true,
    icon: 'fas fa-bell',
    label: i18n('dashboard.notification'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.notificationSend,
  },
  {
    id: '0',
    path: '/product-management',
    exact: true,
    icon: 'fas fa-boxes-stacked',
    label: i18n('dashboard.productManagement'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.storeListingRead,
  },
  {
    id: '0',
    path: '/automat-order',
    exact: true,
    icon: 'fas fa-robot',
    label: i18n('dashboard.automatOrder'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.automatOrderManage,
  },
  {
    id: '0',
    path: '/order-shipment',
    exact: true,
    icon: 'fas fa-truck-fast',
    label: i18n('dashboard.orderShipment'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.orderShipmentManage,
  },
].filter(Boolean);
